In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import normalize

In [2]:
from sklearn.metrics import confusion_matrix
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]
conf_m = confusion_matrix(y_true, y_pred)

In [29]:
row_sums = conf_m.sum(axis=1)
new_matrix = conf_m / row_sums[:, np.newaxis]

In [30]:
new_matrix

array([[1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        ],
       [0.33333333, 0.        , 0.66666667]])

In [14]:
normalize(conf_m, 0,1, axis=0)

TypeError: too many positional arguments

In [2]:
df = pd.read_csv('../../../desktop/wandb_export_2022-08-23T16_06_30.796+03_00.csv')

In [3]:
df =df.iloc[:,[1,4]][:85]

In [4]:
df.describe()

vanilla_longformer_2022-07-09-1804 - Training Accuracy  \
count                                          85.000000        
mean                                            0.693264        
std                                             0.128092        
min                                             0.123016        
25%                                             0.677419        
50%                                             0.719758        
75%                                             0.768145        
max                                             0.808468        

       pmi_longformer_2022-08-22-2334 - Training Accuracy  
count                                          85.000000   
mean                                            0.686137   
std                                             0.123174   
min                                             0.112450   
25%                                             0.666667   
50%                                             0.712851   
75%                                             0.751004   
max                                             0.803213

In [14]:
import numpy as np
from sklearn.preprocessing import normalize

In [10]:
pmi_map = np.array([[1,2,3],[3,4,3],[5,5,9]])

In [28]:
pmi_map

array([[1, 2, 3],
       [3, 4, 3],
       [5, 5, 9]])

In [26]:
pmi_map.sum(axis=1)

array([ 6, 10, 19])

In [29]:
normalize([pmi_map.sum(axis=1)], norm='l1')

array([[0.17142857, 0.28571429, 0.54285714]])